### ISSUE TITLE
Center Button Always Needs to be Draggable

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/radial-menu#86]

**Comment by sedouard** [comment]
Hey @felixrieseberg , looks like the custom menus (in particular metersubmenu) doesn't handle any pointer events on the center button. So from that perspective the custom menus can't do anything about that. When it comes to the Floating user control we do something dumb and just set a flag whenever we are on a menu that shouldn't be dragged. We can also add stuff on RadialMenu to always be draggable when we detect pointerdown + pointer moved on the center button. That would fix the demo.

@PierceDrawboard, the above solution won't help or impact you since you're not using Floating. We agreed that if the metersubmenu just handled pointerdown + pointermoved events, that would be good enough. Pointermoved + pointerdown events should not be getting handled by any control components (RadialMenu only handles CenterButton's tapped event). So should this still just 'work' for you?

**Comment by PierceDrawboard** [comment]
Yep should be fine. I have added our flick and bounce behavior and just
made an attached property for any custom menu that needs the mouse. Our
behavior will then ignore if has the attached property.

On Thu, Oct 15, 2015 at 8:10 AM, Steven Edouard notifications@github.com
wrote:

> Hey @felixrieseberg https://github.com/felixrieseberg , looks like the
> custom menus (in particular metersubmenu) doesn't handle any pointer events
> on the center button. So from that perspective the custom menus can't do
> anything about that. When it comes to the Floating user control we do
> something dumb and just set a flag whenever we are on a menu that shouldn't
> be dragged. We can also add stuff on RadialMenu to always be draggable when
> we detect pointerdown + pointer moved on the center button. That would fix
> the demo.
> 
> @PierceDrawboard https://github.com/PierceDrawboard, the above solution
> won't help or impact you since you're not using Floating. We agreed that if
> the metersubmenu just handled pointerdown + pointermoved events, that would
> be good enough. Pointermoved + pointerdown events should not be getting
> handled by any control components (RadialMenu only handles CenterButton's
> tapped event). So should this still just 'work' for you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CatalystCode/radial-menu/issues/86#issuecomment-148201427
> .

## 

*Pierce Norman *| Software Engineer
Drawboard | www.drawboard.com | Level 11, 356 Collins Street, Melbourne,
Australia.

**Comment by felixrieseberg** [comment]
Well, if it works for you guys I'm closing this. I don't really worry about the demo all too much.
